MVC/Controllers/ContactsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using TelefonRehberi.Models;

namespace TelefonRehberi.Controllers;

public class ContactsController : Controller
{
    private readonly ILogger<ContactsController> _logger;

    private readonly DataContext _context;

    private readonly ContactManage _contactManage;

    private readonly ContactInformationManage _contactInformationManage;

    public ContactsController(ILogger<ContactsController> logger, DataContext context, ContactManage contactManage, ContactInformationManage contactInformationManage)
    {
        _logger = logger;
        _context = context;
        _contactManage = contactManage;
        _contactInformationManage = contactInformationManage;
    }

    public IActionResult Index()
    {
        var contacts = _contactManage.GetContacts();

        for(int i=0; i < contacts.Count(); i++) {
            contacts[i].ContactInformations = _context.ContactInformations.Where(b => b.ContactsUUID == contacts[i].UUID).ToArray();
        }

        return View(contacts);
    }

    public IActionResult GetPersonList()
    {
        return Ok("Get PersonList");
    }

    [HttpPost]
    public IActionResult SavePerson()
    {

        int UUID = int.Parse( Request.Form["UUID"] );
        string InputAd = Request.Form["input_ad"];
        string InputSoyad = Request.Form["input_soyad"];
        string InputFirma = Request.Form["input_firma"];

        string[] InfoType = Request.Form["info_type"];
        string[] InfoContent = Request.Form["info_content"];

        if( UUID == 0 ) {

            try {
                int NewID = _contactManage.AddContact(new Contact {
                    Ad = InputAd,
                    Soyad = InputSoyad,
                    Firma = InputFirma
                });

                for(int i=0; i < InfoType.Count(); i++) {

                    _contactInformationManage.AddInformationToContact(new ContactInformation {
                        InfoType = InfoType[i],
                        InfoContent = InfoContent[i],
                        ContactsUUID = NewID
                    });

                }

                var contacts = _contactManage.GetContacts().Where(d => d.UUID == NewID).ToArray();
                for(int i=0; i < contacts.Count(); i++) {
                    contacts[i].ContactInformations = _context.ContactInformations.Where(b => b.ContactsUUID == contacts[i].UUID).ToArray();
                }

                string returnValue = JsonConvert.SerializeObject(contacts, new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore});

                return Ok(returnValue);

            } catch {
                throw new ArgumentException("Eklenirken bir hata oluştu.");
            }

        } else {

            try {

                _contactManage.UpdateContact(new Contact {
                    UUID = UUID,
                    Ad = InputAd,
                    Soyad = InputSoyad,
                    Firma = InputFirma
                });

                _contactInformationManage.RemoveInformationContact(UUID);

                for(int i=0; i < InfoType.Count(); i++) {

                    _contactInformationManage.AddInformationToContact(new ContactInformation{
                        InfoType = InfoType[i],
                        InfoContent = InfoContent[i],
                        ContactsUUID = UUID
                    });

                }

                var contacts = _contactManage.GetContacts().Where(d => d.UUID == UUID).ToArray();
                for(int i=0; i < contacts.Count(); i++) {
                    contacts[i].ContactInformations = _context.ContactInformations.Where(b => b.ContactsUUID == contacts[i].UUID).ToArray();
                }

                string returnValue = JsonConvert.SerializeObject(contacts, new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore});

                return Ok(returnValue);
            } catch(Exception e) {
                throw new ArgumentException("Güncellenirken bir hata oluştu." + e);
            }

        }

    }

    [HttpPost]
    public IActionResult RemovePerson()
    {
        try {

            int UUID = int.Parse( Request.Form["UUID"] );

            _contactManage.RemoveContact(UUID);

            return Ok("Başarılı");
        } catch(Exception e) {
            throw new ArgumentException("Silinirken bir hata oluştu." + e);
        }

    }

    public IActionResult GetPersonDetails()
    {
        return Ok("GetPersonDetails");
    }

    public IActionResult AddInformationToPerson()
    {
        return Ok("AddInformationToPerson");
    }

    public IActionResult RemoveInformationFromPerson()
    {
        return Ok("RemoveInformationFromPerson");
    }

    public IActionResult GetStatistics()
    {
        return Ok("GetStatistics");
    }

    public IActionResult GetStatisticDetails()
    {
        return Ok("GetStatisticDetails");
    }

    public IActionResult CreateStatistics()
    {
        return Ok("CreateStatistics");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MVC/Controllers/InstallationController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TelefonRehberi.Models;

namespace TelefonRehberi.Controllers;

public class InstallationController : Controller
{
    private readonly ILogger<InstallationController> _logger;

    private readonly ContactManage _contactManage;

    private readonly ContactInformationManage _contactInformationManage;

    public InstallationController(ILogger<InstallationController> logger, ContactManage contactManage, ContactInformationManage contactInformationManage)
    {
        _logger = logger;
        _contactManage = contactManage;
        _contactInformationManage = contactInformationManage;
    }

    public IActionResult Index()
    {

        object[] Contacts = {
            new Contact {
                Ad = "Brad",
                Soyad = "Guerrero",
                Firma = "A Company"
            },
            new Contact {
                Ad = "Gruffydd",
                Soyad = "Macfarlane",
                Firma = "BBB"
            },
            new Contact {
                Ad = "Arley",
                Soyad = "Mcguire",
                Firma = "C Ltd. Şti"
            },
            new Contact {
                Ad = "Madina",
                Soyad = "Whitworth",
                Firma = "A4-Tech"
            },
            new Contact {
                Ad = "Isaac",
                Soyad = "Stephens",
                Firma = "Dell"
            },
            new Contact {
                Ad = "Gwion",
                Soyad = "Clarke",
                Firma = "Asus"
            },
            new Contact {
                Ad = "Bianca",
                Soyad = "Carrillo",
                Firma = "Apple"
            },
            new Contact {
                Ad = "Haydn",
                Soyad = "Connor",
                Firma = "Microsoft"
            },
            new Contact {
                Ad = "Federico",
                Soyad = "Stacey",
                Firma = "Lenovo"
            },
            new Contact {
                Ad = "Gwen",
                Soyad = "Barnard",
                Firma = "IBM"
            },
        };

        object[] CityPool = {
            "Adana", 
            "Ankara", 
            "Antalya", 
            "Aydın", 
            "Bursa", 
            "Çanakkale", 
            "Diyarbakır", 
            "Edirne", 
            "Eskişehir", 
            "Gaziantep", 
            "Hatay", 
            "Mersin", 
            "İstanbul", 
            "İzmir"
        };

        try {

            foreach(Contact contact in Contacts) {
                int UUID = _contactManage.AddContact(contact);
            }

            ViewData["Title"] = "Kurulum";
            ViewBag.InsertedCount = Contacts.Length;

            return View();

        } catch(Exception e) {

            throw new ArgumentException("Kurulum aşamasında bir hata meydana geldi. \n\n" + e);

        }
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MVC/Controllers/ReportsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using TelefonRehberi.Models;

namespace TelefonRehberi.Controllers;

public class ReportsController : Controller
{
    private readonly ILogger<ContactsController> _logger;

    private readonly DataContext _context;

    private readonly ContactManage _contactManage;

    private readonly ContactInformationManage _contactInformationManage;

    private readonly ReportManage _reportManage;

    public ReportsController(ILogger<ContactsController> logger, DataContext context, ContactManage contactManage, ContactInformationManage contactInformationManage, ReportManage reportManage)
    {
        _logger = logger;
        _context = context;
        _contactManage = contactManage;
        _contactInformationManage = contactInformationManage;
        _reportManage = reportManage;
    }

    public IActionResult Index()
    {
        var reports = _reportManage.GetReports();

        JsonConvert.SerializeObject(reports, new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore});

        return View(reports);
    }

    public IActionResult Create()
    {
        try {

            _reportManage.CreateReport();

            return Ok( "Rapor oluşturuldu" );

        } catch {
            return BadRequest("Oluşturma anında bir hata meydana geldi");
        }

    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TelefonRehberi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Contacts" asp-action="Index">TelefonRehberi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacts" asp-action="Index">Rehber</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reports" asp-action="Index">Raporlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Installation" asp-action="Index">Kurulum</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <button class="btn btn-primary" id="yeniKisiEkle">+ Yeni Kişi Ekle</button>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TelefonRehberi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>